### ISSUE TITLE
Week 4

### ISSUE THREAD

**Issue by AAMerritt109J** [UD-PCS-Foundations-of-R-Fall-2021/week_04#1]
bad6610 @rharrington31

**Comment by rharrington31** [comment]
1. Good.
2. This works. Careful, though. `read.csv2` is the base R implementation of `readr::read_csv2`. Also, no need to use `read.csv2` as `read_csv` would work fine. The dataset is comma delimited by default.
3. Summary does accomplish this, though consider utilizing `across`!
4. You're close here. You would just need `is.na` as opposed to `is.na.data.frame`. R will handle the method by default for you. If that were fixed, this should work.
5. `across` will only work inside of a `dplyr` function, such as `mutate` or `summarize`. The `sum` function should be located inside of `across`, such as `mutate(across(columns, ~sum(.)))`
6. This is also close, but your `condition` is not set correctly.  You have it reversed: `is.na(column_name)` would work.
7. Your `true` and `false` do not need `across`. You can just simply write it as `true = mean(.)` and `false = .`. You could also consider a strategy such as utilizing `replace_na`.
8. `starts_with` will only work with column names inside of a `select` statement or an argument that utilizes tidy-select standards. Figure out the different ways someone might state "yes" or "no" and then pair that with `case_when`.
9. Consider if this would work as a graph. There are a very large number of locations and burritos. This did not yield an interpretable graph.
